language: android
android:
        components:
                - platform-tools
                - build-tools-25.0.0
                - android-22
                - extra-android-m2repository
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew
